behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 264
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.3
        demo_path: ../../Demos/JumpRecord_4.demo
        use_actions: false

    behavioral_cloning:
      strength: 0.4
      steps: 750000
      demo_path: ../../Demos/JumpRecord_4.demo

    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true